//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Group) DeepCopyInto(out *Group) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Group.
func (in *Group) DeepCopy() *Group {
	if in == nil {
		return nil
	}
	out := new(Group)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Group) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupInitParameters) DeepCopyInto(out *GroupInitParameters) {
	*out = *in
	if in.AdminPrivileges != nil {
		in, out := &in.AdminPrivileges, &out.AdminPrivileges
		*out = new(bool)
		**out = **in
	}
	if in.AutoJoin != nil {
		in, out := &in.AutoJoin, &out.AutoJoin
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ExternalID != nil {
		in, out := &in.ExternalID, &out.ExternalID
		*out = new(string)
		**out = **in
	}
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.UseGroupMembersResource != nil {
		in, out := &in.UseGroupMembersResource, &out.UseGroupMembersResource
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupInitParameters.
func (in *GroupInitParameters) DeepCopy() *GroupInitParameters {
	if in == nil {
		return nil
	}
	out := new(GroupInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupList) DeepCopyInto(out *GroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Group, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupList.
func (in *GroupList) DeepCopy() *GroupList {
	if in == nil {
		return nil
	}
	out := new(GroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupObservation) DeepCopyInto(out *GroupObservation) {
	*out = *in
	if in.AdminPrivileges != nil {
		in, out := &in.AdminPrivileges, &out.AdminPrivileges
		*out = new(bool)
		**out = **in
	}
	if in.AutoJoin != nil {
		in, out := &in.AutoJoin, &out.AutoJoin
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ExternalID != nil {
		in, out := &in.ExternalID, &out.ExternalID
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(string)
		**out = **in
	}
	if in.RealmAttributes != nil {
		in, out := &in.RealmAttributes, &out.RealmAttributes
		*out = new(string)
		**out = **in
	}
	if in.UseGroupMembersResource != nil {
		in, out := &in.UseGroupMembersResource, &out.UseGroupMembersResource
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupObservation.
func (in *GroupObservation) DeepCopy() *GroupObservation {
	if in == nil {
		return nil
	}
	out := new(GroupObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupParameters) DeepCopyInto(out *GroupParameters) {
	*out = *in
	if in.AdminPrivileges != nil {
		in, out := &in.AdminPrivileges, &out.AdminPrivileges
		*out = new(bool)
		**out = **in
	}
	if in.AutoJoin != nil {
		in, out := &in.AutoJoin, &out.AutoJoin
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ExternalID != nil {
		in, out := &in.ExternalID, &out.ExternalID
		*out = new(string)
		**out = **in
	}
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.UseGroupMembersResource != nil {
		in, out := &in.UseGroupMembersResource, &out.UseGroupMembersResource
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupParameters.
func (in *GroupParameters) DeepCopy() *GroupParameters {
	if in == nil {
		return nil
	}
	out := new(GroupParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupSpec) DeepCopyInto(out *GroupSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupSpec.
func (in *GroupSpec) DeepCopy() *GroupSpec {
	if in == nil {
		return nil
	}
	out := new(GroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupStatus) DeepCopyInto(out *GroupStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupStatus.
func (in *GroupStatus) DeepCopy() *GroupStatus {
	if in == nil {
		return nil
	}
	out := new(GroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLSettings) DeepCopyInto(out *SAMLSettings) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLSettings.
func (in *SAMLSettings) DeepCopy() *SAMLSettings {
	if in == nil {
		return nil
	}
	out := new(SAMLSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SAMLSettings) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLSettingsInitParameters) DeepCopyInto(out *SAMLSettingsInitParameters) {
	*out = *in
	if in.AllowUserToAccessProfile != nil {
		in, out := &in.AllowUserToAccessProfile, &out.AllowUserToAccessProfile
		*out = new(bool)
		**out = **in
	}
	if in.AutoRedirect != nil {
		in, out := &in.AutoRedirect, &out.AutoRedirect
		*out = new(bool)
		**out = **in
	}
	if in.AutoUserCreation != nil {
		in, out := &in.AutoUserCreation, &out.AutoUserCreation
		*out = new(bool)
		**out = **in
	}
	out.CertificateSecretRef = in.CertificateSecretRef
	if in.EmailAttribute != nil {
		in, out := &in.EmailAttribute, &out.EmailAttribute
		*out = new(string)
		**out = **in
	}
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.GroupAttribute != nil {
		in, out := &in.GroupAttribute, &out.GroupAttribute
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupSettings != nil {
		in, out := &in.LdapGroupSettings, &out.LdapGroupSettings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.LoginURL != nil {
		in, out := &in.LoginURL, &out.LoginURL
		*out = new(string)
		**out = **in
	}
	if in.LogoutURL != nil {
		in, out := &in.LogoutURL, &out.LogoutURL
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameIDAttribute != nil {
		in, out := &in.NameIDAttribute, &out.NameIDAttribute
		*out = new(string)
		**out = **in
	}
	if in.ServiceProviderName != nil {
		in, out := &in.ServiceProviderName, &out.ServiceProviderName
		*out = new(string)
		**out = **in
	}
	if in.SyncGroups != nil {
		in, out := &in.SyncGroups, &out.SyncGroups
		*out = new(bool)
		**out = **in
	}
	if in.UseEncryptedAssertion != nil {
		in, out := &in.UseEncryptedAssertion, &out.UseEncryptedAssertion
		*out = new(bool)
		**out = **in
	}
	if in.VerifyAudienceRestriction != nil {
		in, out := &in.VerifyAudienceRestriction, &out.VerifyAudienceRestriction
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLSettingsInitParameters.
func (in *SAMLSettingsInitParameters) DeepCopy() *SAMLSettingsInitParameters {
	if in == nil {
		return nil
	}
	out := new(SAMLSettingsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLSettingsList) DeepCopyInto(out *SAMLSettingsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SAMLSettings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLSettingsList.
func (in *SAMLSettingsList) DeepCopy() *SAMLSettingsList {
	if in == nil {
		return nil
	}
	out := new(SAMLSettingsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SAMLSettingsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLSettingsObservation) DeepCopyInto(out *SAMLSettingsObservation) {
	*out = *in
	if in.AllowUserToAccessProfile != nil {
		in, out := &in.AllowUserToAccessProfile, &out.AllowUserToAccessProfile
		*out = new(bool)
		**out = **in
	}
	if in.AutoRedirect != nil {
		in, out := &in.AutoRedirect, &out.AutoRedirect
		*out = new(bool)
		**out = **in
	}
	if in.AutoUserCreation != nil {
		in, out := &in.AutoUserCreation, &out.AutoUserCreation
		*out = new(bool)
		**out = **in
	}
	if in.EmailAttribute != nil {
		in, out := &in.EmailAttribute, &out.EmailAttribute
		*out = new(string)
		**out = **in
	}
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.GroupAttribute != nil {
		in, out := &in.GroupAttribute, &out.GroupAttribute
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupSettings != nil {
		in, out := &in.LdapGroupSettings, &out.LdapGroupSettings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.LoginURL != nil {
		in, out := &in.LoginURL, &out.LoginURL
		*out = new(string)
		**out = **in
	}
	if in.LogoutURL != nil {
		in, out := &in.LogoutURL, &out.LogoutURL
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameIDAttribute != nil {
		in, out := &in.NameIDAttribute, &out.NameIDAttribute
		*out = new(string)
		**out = **in
	}
	if in.ServiceProviderName != nil {
		in, out := &in.ServiceProviderName, &out.ServiceProviderName
		*out = new(string)
		**out = **in
	}
	if in.SyncGroups != nil {
		in, out := &in.SyncGroups, &out.SyncGroups
		*out = new(bool)
		**out = **in
	}
	if in.UseEncryptedAssertion != nil {
		in, out := &in.UseEncryptedAssertion, &out.UseEncryptedAssertion
		*out = new(bool)
		**out = **in
	}
	if in.VerifyAudienceRestriction != nil {
		in, out := &in.VerifyAudienceRestriction, &out.VerifyAudienceRestriction
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLSettingsObservation.
func (in *SAMLSettingsObservation) DeepCopy() *SAMLSettingsObservation {
	if in == nil {
		return nil
	}
	out := new(SAMLSettingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLSettingsParameters) DeepCopyInto(out *SAMLSettingsParameters) {
	*out = *in
	if in.AllowUserToAccessProfile != nil {
		in, out := &in.AllowUserToAccessProfile, &out.AllowUserToAccessProfile
		*out = new(bool)
		**out = **in
	}
	if in.AutoRedirect != nil {
		in, out := &in.AutoRedirect, &out.AutoRedirect
		*out = new(bool)
		**out = **in
	}
	if in.AutoUserCreation != nil {
		in, out := &in.AutoUserCreation, &out.AutoUserCreation
		*out = new(bool)
		**out = **in
	}
	out.CertificateSecretRef = in.CertificateSecretRef
	if in.EmailAttribute != nil {
		in, out := &in.EmailAttribute, &out.EmailAttribute
		*out = new(string)
		**out = **in
	}
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.GroupAttribute != nil {
		in, out := &in.GroupAttribute, &out.GroupAttribute
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupSettings != nil {
		in, out := &in.LdapGroupSettings, &out.LdapGroupSettings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.LoginURL != nil {
		in, out := &in.LoginURL, &out.LoginURL
		*out = new(string)
		**out = **in
	}
	if in.LogoutURL != nil {
		in, out := &in.LogoutURL, &out.LogoutURL
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameIDAttribute != nil {
		in, out := &in.NameIDAttribute, &out.NameIDAttribute
		*out = new(string)
		**out = **in
	}
	if in.ServiceProviderName != nil {
		in, out := &in.ServiceProviderName, &out.ServiceProviderName
		*out = new(string)
		**out = **in
	}
	if in.SyncGroups != nil {
		in, out := &in.SyncGroups, &out.SyncGroups
		*out = new(bool)
		**out = **in
	}
	if in.UseEncryptedAssertion != nil {
		in, out := &in.UseEncryptedAssertion, &out.UseEncryptedAssertion
		*out = new(bool)
		**out = **in
	}
	if in.VerifyAudienceRestriction != nil {
		in, out := &in.VerifyAudienceRestriction, &out.VerifyAudienceRestriction
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLSettingsParameters.
func (in *SAMLSettingsParameters) DeepCopy() *SAMLSettingsParameters {
	if in == nil {
		return nil
	}
	out := new(SAMLSettingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLSettingsSpec) DeepCopyInto(out *SAMLSettingsSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLSettingsSpec.
func (in *SAMLSettingsSpec) DeepCopy() *SAMLSettingsSpec {
	if in == nil {
		return nil
	}
	out := new(SAMLSettingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLSettingsStatus) DeepCopyInto(out *SAMLSettingsStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLSettingsStatus.
func (in *SAMLSettingsStatus) DeepCopy() *SAMLSettingsStatus {
	if in == nil {
		return nil
	}
	out := new(SAMLSettingsStatus)
	in.DeepCopyInto(out)
	return out
}
