//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Group) DeepCopyInto(out *Group) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Group.
func (in *Group) DeepCopy() *Group {
	if in == nil {
		return nil
	}
	out := new(Group)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Group) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupInitParameters) DeepCopyInto(out *GroupInitParameters) {
	*out = *in
	if in.AdminPrivileges != nil {
		in, out := &in.AdminPrivileges, &out.AdminPrivileges
		*out = new(bool)
		**out = **in
	}
	if in.AutoJoin != nil {
		in, out := &in.AutoJoin, &out.AutoJoin
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ExternalID != nil {
		in, out := &in.ExternalID, &out.ExternalID
		*out = new(string)
		**out = **in
	}
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.UseGroupMembersResource != nil {
		in, out := &in.UseGroupMembersResource, &out.UseGroupMembersResource
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupInitParameters.
func (in *GroupInitParameters) DeepCopy() *GroupInitParameters {
	if in == nil {
		return nil
	}
	out := new(GroupInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupList) DeepCopyInto(out *GroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Group, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupList.
func (in *GroupList) DeepCopy() *GroupList {
	if in == nil {
		return nil
	}
	out := new(GroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupObservation) DeepCopyInto(out *GroupObservation) {
	*out = *in
	if in.AdminPrivileges != nil {
		in, out := &in.AdminPrivileges, &out.AdminPrivileges
		*out = new(bool)
		**out = **in
	}
	if in.AutoJoin != nil {
		in, out := &in.AutoJoin, &out.AutoJoin
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ExternalID != nil {
		in, out := &in.ExternalID, &out.ExternalID
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(string)
		**out = **in
	}
	if in.RealmAttributes != nil {
		in, out := &in.RealmAttributes, &out.RealmAttributes
		*out = new(string)
		**out = **in
	}
	if in.UseGroupMembersResource != nil {
		in, out := &in.UseGroupMembersResource, &out.UseGroupMembersResource
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupObservation.
func (in *GroupObservation) DeepCopy() *GroupObservation {
	if in == nil {
		return nil
	}
	out := new(GroupObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupParameters) DeepCopyInto(out *GroupParameters) {
	*out = *in
	if in.AdminPrivileges != nil {
		in, out := &in.AdminPrivileges, &out.AdminPrivileges
		*out = new(bool)
		**out = **in
	}
	if in.AutoJoin != nil {
		in, out := &in.AutoJoin, &out.AutoJoin
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ExternalID != nil {
		in, out := &in.ExternalID, &out.ExternalID
		*out = new(string)
		**out = **in
	}
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.UseGroupMembersResource != nil {
		in, out := &in.UseGroupMembersResource, &out.UseGroupMembersResource
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupParameters.
func (in *GroupParameters) DeepCopy() *GroupParameters {
	if in == nil {
		return nil
	}
	out := new(GroupParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupSpec) DeepCopyInto(out *GroupSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupSpec.
func (in *GroupSpec) DeepCopy() *GroupSpec {
	if in == nil {
		return nil
	}
	out := new(GroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupStatus) DeepCopyInto(out *GroupStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupStatus.
func (in *GroupStatus) DeepCopy() *GroupStatus {
	if in == nil {
		return nil
	}
	out := new(GroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCConfiguration) DeepCopyInto(out *OIDCConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCConfiguration.
func (in *OIDCConfiguration) DeepCopy() *OIDCConfiguration {
	if in == nil {
		return nil
	}
	out := new(OIDCConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OIDCConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCConfigurationInitParameters) DeepCopyInto(out *OIDCConfigurationInitParameters) {
	*out = *in
	if in.Audience != nil {
		in, out := &in.Audience, &out.Audience
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EnablePermissiveConfiguration != nil {
		in, out := &in.EnablePermissiveConfiguration, &out.EnablePermissiveConfiguration
		*out = new(bool)
		**out = **in
	}
	if in.IssuerURL != nil {
		in, out := &in.IssuerURL, &out.IssuerURL
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.ProjectKey != nil {
		in, out := &in.ProjectKey, &out.ProjectKey
		*out = new(string)
		**out = **in
	}
	if in.ProviderType != nil {
		in, out := &in.ProviderType, &out.ProviderType
		*out = new(string)
		**out = **in
	}
	if in.UseDefaultProxy != nil {
		in, out := &in.UseDefaultProxy, &out.UseDefaultProxy
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCConfigurationInitParameters.
func (in *OIDCConfigurationInitParameters) DeepCopy() *OIDCConfigurationInitParameters {
	if in == nil {
		return nil
	}
	out := new(OIDCConfigurationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCConfigurationList) DeepCopyInto(out *OIDCConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OIDCConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCConfigurationList.
func (in *OIDCConfigurationList) DeepCopy() *OIDCConfigurationList {
	if in == nil {
		return nil
	}
	out := new(OIDCConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OIDCConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCConfigurationObservation) DeepCopyInto(out *OIDCConfigurationObservation) {
	*out = *in
	if in.Audience != nil {
		in, out := &in.Audience, &out.Audience
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EnablePermissiveConfiguration != nil {
		in, out := &in.EnablePermissiveConfiguration, &out.EnablePermissiveConfiguration
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IssuerURL != nil {
		in, out := &in.IssuerURL, &out.IssuerURL
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.ProjectKey != nil {
		in, out := &in.ProjectKey, &out.ProjectKey
		*out = new(string)
		**out = **in
	}
	if in.ProviderType != nil {
		in, out := &in.ProviderType, &out.ProviderType
		*out = new(string)
		**out = **in
	}
	if in.UseDefaultProxy != nil {
		in, out := &in.UseDefaultProxy, &out.UseDefaultProxy
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCConfigurationObservation.
func (in *OIDCConfigurationObservation) DeepCopy() *OIDCConfigurationObservation {
	if in == nil {
		return nil
	}
	out := new(OIDCConfigurationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCConfigurationParameters) DeepCopyInto(out *OIDCConfigurationParameters) {
	*out = *in
	if in.Audience != nil {
		in, out := &in.Audience, &out.Audience
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EnablePermissiveConfiguration != nil {
		in, out := &in.EnablePermissiveConfiguration, &out.EnablePermissiveConfiguration
		*out = new(bool)
		**out = **in
	}
	if in.IssuerURL != nil {
		in, out := &in.IssuerURL, &out.IssuerURL
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.ProjectKey != nil {
		in, out := &in.ProjectKey, &out.ProjectKey
		*out = new(string)
		**out = **in
	}
	if in.ProviderType != nil {
		in, out := &in.ProviderType, &out.ProviderType
		*out = new(string)
		**out = **in
	}
	if in.UseDefaultProxy != nil {
		in, out := &in.UseDefaultProxy, &out.UseDefaultProxy
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCConfigurationParameters.
func (in *OIDCConfigurationParameters) DeepCopy() *OIDCConfigurationParameters {
	if in == nil {
		return nil
	}
	out := new(OIDCConfigurationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCConfigurationSpec) DeepCopyInto(out *OIDCConfigurationSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCConfigurationSpec.
func (in *OIDCConfigurationSpec) DeepCopy() *OIDCConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(OIDCConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCConfigurationStatus) DeepCopyInto(out *OIDCConfigurationStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCConfigurationStatus.
func (in *OIDCConfigurationStatus) DeepCopy() *OIDCConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(OIDCConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReverseProxy) DeepCopyInto(out *ReverseProxy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReverseProxy.
func (in *ReverseProxy) DeepCopy() *ReverseProxy {
	if in == nil {
		return nil
	}
	out := new(ReverseProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReverseProxy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReverseProxyInitParameters) DeepCopyInto(out *ReverseProxyInitParameters) {
	*out = *in
	if in.DockerReverseProxyMethod != nil {
		in, out := &in.DockerReverseProxyMethod, &out.DockerReverseProxyMethod
		*out = new(string)
		**out = **in
	}
	if in.HTTPPort != nil {
		in, out := &in.HTTPPort, &out.HTTPPort
		*out = new(float64)
		**out = **in
	}
	if in.HTTPSPort != nil {
		in, out := &in.HTTPSPort, &out.HTTPSPort
		*out = new(float64)
		**out = **in
	}
	if in.InternalHostname != nil {
		in, out := &in.InternalHostname, &out.InternalHostname
		*out = new(string)
		**out = **in
	}
	if in.PublicServerName != nil {
		in, out := &in.PublicServerName, &out.PublicServerName
		*out = new(string)
		**out = **in
	}
	if in.SSLCertificatePath != nil {
		in, out := &in.SSLCertificatePath, &out.SSLCertificatePath
		*out = new(string)
		**out = **in
	}
	if in.SSLKeyPath != nil {
		in, out := &in.SSLKeyPath, &out.SSLKeyPath
		*out = new(string)
		**out = **in
	}
	if in.ServerProvider != nil {
		in, out := &in.ServerProvider, &out.ServerProvider
		*out = new(string)
		**out = **in
	}
	if in.UseHTTPS != nil {
		in, out := &in.UseHTTPS, &out.UseHTTPS
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReverseProxyInitParameters.
func (in *ReverseProxyInitParameters) DeepCopy() *ReverseProxyInitParameters {
	if in == nil {
		return nil
	}
	out := new(ReverseProxyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReverseProxyList) DeepCopyInto(out *ReverseProxyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ReverseProxy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReverseProxyList.
func (in *ReverseProxyList) DeepCopy() *ReverseProxyList {
	if in == nil {
		return nil
	}
	out := new(ReverseProxyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReverseProxyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReverseProxyObservation) DeepCopyInto(out *ReverseProxyObservation) {
	*out = *in
	if in.DockerReverseProxyMethod != nil {
		in, out := &in.DockerReverseProxyMethod, &out.DockerReverseProxyMethod
		*out = new(string)
		**out = **in
	}
	if in.HTTPPort != nil {
		in, out := &in.HTTPPort, &out.HTTPPort
		*out = new(float64)
		**out = **in
	}
	if in.HTTPSPort != nil {
		in, out := &in.HTTPSPort, &out.HTTPSPort
		*out = new(float64)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.InternalHostname != nil {
		in, out := &in.InternalHostname, &out.InternalHostname
		*out = new(string)
		**out = **in
	}
	if in.PublicServerName != nil {
		in, out := &in.PublicServerName, &out.PublicServerName
		*out = new(string)
		**out = **in
	}
	if in.SSLCertificatePath != nil {
		in, out := &in.SSLCertificatePath, &out.SSLCertificatePath
		*out = new(string)
		**out = **in
	}
	if in.SSLKeyPath != nil {
		in, out := &in.SSLKeyPath, &out.SSLKeyPath
		*out = new(string)
		**out = **in
	}
	if in.ServerProvider != nil {
		in, out := &in.ServerProvider, &out.ServerProvider
		*out = new(string)
		**out = **in
	}
	if in.UseHTTPS != nil {
		in, out := &in.UseHTTPS, &out.UseHTTPS
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReverseProxyObservation.
func (in *ReverseProxyObservation) DeepCopy() *ReverseProxyObservation {
	if in == nil {
		return nil
	}
	out := new(ReverseProxyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReverseProxyParameters) DeepCopyInto(out *ReverseProxyParameters) {
	*out = *in
	if in.DockerReverseProxyMethod != nil {
		in, out := &in.DockerReverseProxyMethod, &out.DockerReverseProxyMethod
		*out = new(string)
		**out = **in
	}
	if in.HTTPPort != nil {
		in, out := &in.HTTPPort, &out.HTTPPort
		*out = new(float64)
		**out = **in
	}
	if in.HTTPSPort != nil {
		in, out := &in.HTTPSPort, &out.HTTPSPort
		*out = new(float64)
		**out = **in
	}
	if in.InternalHostname != nil {
		in, out := &in.InternalHostname, &out.InternalHostname
		*out = new(string)
		**out = **in
	}
	if in.PublicServerName != nil {
		in, out := &in.PublicServerName, &out.PublicServerName
		*out = new(string)
		**out = **in
	}
	if in.SSLCertificatePath != nil {
		in, out := &in.SSLCertificatePath, &out.SSLCertificatePath
		*out = new(string)
		**out = **in
	}
	if in.SSLKeyPath != nil {
		in, out := &in.SSLKeyPath, &out.SSLKeyPath
		*out = new(string)
		**out = **in
	}
	if in.ServerProvider != nil {
		in, out := &in.ServerProvider, &out.ServerProvider
		*out = new(string)
		**out = **in
	}
	if in.UseHTTPS != nil {
		in, out := &in.UseHTTPS, &out.UseHTTPS
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReverseProxyParameters.
func (in *ReverseProxyParameters) DeepCopy() *ReverseProxyParameters {
	if in == nil {
		return nil
	}
	out := new(ReverseProxyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReverseProxySpec) DeepCopyInto(out *ReverseProxySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReverseProxySpec.
func (in *ReverseProxySpec) DeepCopy() *ReverseProxySpec {
	if in == nil {
		return nil
	}
	out := new(ReverseProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReverseProxyStatus) DeepCopyInto(out *ReverseProxyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReverseProxyStatus.
func (in *ReverseProxyStatus) DeepCopy() *ReverseProxyStatus {
	if in == nil {
		return nil
	}
	out := new(ReverseProxyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLSettings) DeepCopyInto(out *SAMLSettings) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLSettings.
func (in *SAMLSettings) DeepCopy() *SAMLSettings {
	if in == nil {
		return nil
	}
	out := new(SAMLSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SAMLSettings) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLSettingsInitParameters) DeepCopyInto(out *SAMLSettingsInitParameters) {
	*out = *in
	if in.AllowUserToAccessProfile != nil {
		in, out := &in.AllowUserToAccessProfile, &out.AllowUserToAccessProfile
		*out = new(bool)
		**out = **in
	}
	if in.AutoRedirect != nil {
		in, out := &in.AutoRedirect, &out.AutoRedirect
		*out = new(bool)
		**out = **in
	}
	if in.AutoUserCreation != nil {
		in, out := &in.AutoUserCreation, &out.AutoUserCreation
		*out = new(bool)
		**out = **in
	}
	out.CertificateSecretRef = in.CertificateSecretRef
	if in.EmailAttribute != nil {
		in, out := &in.EmailAttribute, &out.EmailAttribute
		*out = new(string)
		**out = **in
	}
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.GroupAttribute != nil {
		in, out := &in.GroupAttribute, &out.GroupAttribute
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupSettings != nil {
		in, out := &in.LdapGroupSettings, &out.LdapGroupSettings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.LoginURL != nil {
		in, out := &in.LoginURL, &out.LoginURL
		*out = new(string)
		**out = **in
	}
	if in.LogoutURL != nil {
		in, out := &in.LogoutURL, &out.LogoutURL
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameIDAttribute != nil {
		in, out := &in.NameIDAttribute, &out.NameIDAttribute
		*out = new(string)
		**out = **in
	}
	if in.ServiceProviderName != nil {
		in, out := &in.ServiceProviderName, &out.ServiceProviderName
		*out = new(string)
		**out = **in
	}
	if in.SyncGroups != nil {
		in, out := &in.SyncGroups, &out.SyncGroups
		*out = new(bool)
		**out = **in
	}
	if in.UseEncryptedAssertion != nil {
		in, out := &in.UseEncryptedAssertion, &out.UseEncryptedAssertion
		*out = new(bool)
		**out = **in
	}
	if in.VerifyAudienceRestriction != nil {
		in, out := &in.VerifyAudienceRestriction, &out.VerifyAudienceRestriction
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLSettingsInitParameters.
func (in *SAMLSettingsInitParameters) DeepCopy() *SAMLSettingsInitParameters {
	if in == nil {
		return nil
	}
	out := new(SAMLSettingsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLSettingsList) DeepCopyInto(out *SAMLSettingsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SAMLSettings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLSettingsList.
func (in *SAMLSettingsList) DeepCopy() *SAMLSettingsList {
	if in == nil {
		return nil
	}
	out := new(SAMLSettingsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SAMLSettingsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLSettingsObservation) DeepCopyInto(out *SAMLSettingsObservation) {
	*out = *in
	if in.AllowUserToAccessProfile != nil {
		in, out := &in.AllowUserToAccessProfile, &out.AllowUserToAccessProfile
		*out = new(bool)
		**out = **in
	}
	if in.AutoRedirect != nil {
		in, out := &in.AutoRedirect, &out.AutoRedirect
		*out = new(bool)
		**out = **in
	}
	if in.AutoUserCreation != nil {
		in, out := &in.AutoUserCreation, &out.AutoUserCreation
		*out = new(bool)
		**out = **in
	}
	if in.EmailAttribute != nil {
		in, out := &in.EmailAttribute, &out.EmailAttribute
		*out = new(string)
		**out = **in
	}
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.GroupAttribute != nil {
		in, out := &in.GroupAttribute, &out.GroupAttribute
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupSettings != nil {
		in, out := &in.LdapGroupSettings, &out.LdapGroupSettings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.LoginURL != nil {
		in, out := &in.LoginURL, &out.LoginURL
		*out = new(string)
		**out = **in
	}
	if in.LogoutURL != nil {
		in, out := &in.LogoutURL, &out.LogoutURL
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameIDAttribute != nil {
		in, out := &in.NameIDAttribute, &out.NameIDAttribute
		*out = new(string)
		**out = **in
	}
	if in.ServiceProviderName != nil {
		in, out := &in.ServiceProviderName, &out.ServiceProviderName
		*out = new(string)
		**out = **in
	}
	if in.SyncGroups != nil {
		in, out := &in.SyncGroups, &out.SyncGroups
		*out = new(bool)
		**out = **in
	}
	if in.UseEncryptedAssertion != nil {
		in, out := &in.UseEncryptedAssertion, &out.UseEncryptedAssertion
		*out = new(bool)
		**out = **in
	}
	if in.VerifyAudienceRestriction != nil {
		in, out := &in.VerifyAudienceRestriction, &out.VerifyAudienceRestriction
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLSettingsObservation.
func (in *SAMLSettingsObservation) DeepCopy() *SAMLSettingsObservation {
	if in == nil {
		return nil
	}
	out := new(SAMLSettingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLSettingsParameters) DeepCopyInto(out *SAMLSettingsParameters) {
	*out = *in
	if in.AllowUserToAccessProfile != nil {
		in, out := &in.AllowUserToAccessProfile, &out.AllowUserToAccessProfile
		*out = new(bool)
		**out = **in
	}
	if in.AutoRedirect != nil {
		in, out := &in.AutoRedirect, &out.AutoRedirect
		*out = new(bool)
		**out = **in
	}
	if in.AutoUserCreation != nil {
		in, out := &in.AutoUserCreation, &out.AutoUserCreation
		*out = new(bool)
		**out = **in
	}
	out.CertificateSecretRef = in.CertificateSecretRef
	if in.EmailAttribute != nil {
		in, out := &in.EmailAttribute, &out.EmailAttribute
		*out = new(string)
		**out = **in
	}
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.GroupAttribute != nil {
		in, out := &in.GroupAttribute, &out.GroupAttribute
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupSettings != nil {
		in, out := &in.LdapGroupSettings, &out.LdapGroupSettings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.LoginURL != nil {
		in, out := &in.LoginURL, &out.LoginURL
		*out = new(string)
		**out = **in
	}
	if in.LogoutURL != nil {
		in, out := &in.LogoutURL, &out.LogoutURL
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameIDAttribute != nil {
		in, out := &in.NameIDAttribute, &out.NameIDAttribute
		*out = new(string)
		**out = **in
	}
	if in.ServiceProviderName != nil {
		in, out := &in.ServiceProviderName, &out.ServiceProviderName
		*out = new(string)
		**out = **in
	}
	if in.SyncGroups != nil {
		in, out := &in.SyncGroups, &out.SyncGroups
		*out = new(bool)
		**out = **in
	}
	if in.UseEncryptedAssertion != nil {
		in, out := &in.UseEncryptedAssertion, &out.UseEncryptedAssertion
		*out = new(bool)
		**out = **in
	}
	if in.VerifyAudienceRestriction != nil {
		in, out := &in.VerifyAudienceRestriction, &out.VerifyAudienceRestriction
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLSettingsParameters.
func (in *SAMLSettingsParameters) DeepCopy() *SAMLSettingsParameters {
	if in == nil {
		return nil
	}
	out := new(SAMLSettingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLSettingsSpec) DeepCopyInto(out *SAMLSettingsSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLSettingsSpec.
func (in *SAMLSettingsSpec) DeepCopy() *SAMLSettingsSpec {
	if in == nil {
		return nil
	}
	out := new(SAMLSettingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLSettingsStatus) DeepCopyInto(out *SAMLSettingsStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLSettingsStatus.
func (in *SAMLSettingsStatus) DeepCopy() *SAMLSettingsStatus {
	if in == nil {
		return nil
	}
	out := new(SAMLSettingsStatus)
	in.DeepCopyInto(out)
	return out
}
