// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *CrowdSettings) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GlobalRole) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Group) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *HTTPSSOSettings) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OIDCConfiguration) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ReverseProxy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SAMLSettings) Hub() {}
