// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type GroupMembersInitParameters struct {

	// (Set of String) List of users assigned to the group.
	// List of users assigned to the group.
	// +listType=set
	Members []*string `json:"members,omitempty" tf:"members,omitempty"`
}

type GroupMembersObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Set of String) List of users assigned to the group.
	// List of users assigned to the group.
	// +listType=set
	Members []*string `json:"members,omitempty" tf:"members,omitempty"`
}

type GroupMembersParameters struct {

	// (Set of String) List of users assigned to the group.
	// List of users assigned to the group.
	// +kubebuilder:validation:Optional
	// +listType=set
	Members []*string `json:"members,omitempty" tf:"members,omitempty"`
}

// GroupMembersSpec defines the desired state of GroupMembers
type GroupMembersSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            GroupMembersParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GroupMembersInitParameters `json:"initProvider,omitempty"`
}

// GroupMembersStatus defines the observed state of GroupMembers.
type GroupMembersStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GroupMembersObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GroupMembers is the Schema for the GroupMemberss API. Provides a resource to manage group membership. See JFrog documentation https://jfrog.com/help/r/jfrog-platform-administration-documentation/assign-users-to-groups for more details.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,jfrog-platform}
type GroupMembers struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.members) || (has(self.initProvider) && has(self.initProvider.members))",message="spec.forProvider.members is a required parameter"
	Spec   GroupMembersSpec   `json:"spec"`
	Status GroupMembersStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GroupMembersList contains a list of GroupMemberss
type GroupMembersList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GroupMembers `json:"items"`
}

// Repository type metadata.
var (
	GroupMembers_Kind             = "GroupMembers"
	GroupMembers_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GroupMembers_Kind}.String()
	GroupMembers_KindAPIVersion   = GroupMembers_Kind + "." + CRDGroupVersion.String()
	GroupMembers_GroupVersionKind = CRDGroupVersion.WithKind(GroupMembers_Kind)
)

func init() {
	SchemeBuilder.Register(&GroupMembers{}, &GroupMembersList{})
}
