// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type EmailsInitParameters struct {

	// (Boolean)
	Primary *bool `json:"primary,omitempty" tf:"primary,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type EmailsObservation struct {

	// (Boolean)
	Primary *bool `json:"primary,omitempty" tf:"primary,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type EmailsParameters struct {

	// (Boolean)
	// +kubebuilder:validation:Optional
	Primary *bool `json:"primary" tf:"primary,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type GroupsInitParameters struct {

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type GroupsObservation struct {

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type GroupsParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type SCIMUserInitParameters struct {

	// (Boolean)
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (Attributes Set) (see below for nested schema)
	Emails []EmailsInitParameters `json:"emails,omitempty" tf:"emails,omitempty"`

	// (String)
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type SCIMUserObservation struct {

	// (Boolean)
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (Attributes Set) (see below for nested schema)
	Emails []EmailsObservation `json:"emails,omitempty" tf:"emails,omitempty"`

	// (Attributes Set) (see below for nested schema)
	Groups []GroupsObservation `json:"groups,omitempty" tf:"groups,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Map of String)
	// +mapType=granular
	Meta map[string]*string `json:"meta,omitempty" tf:"meta,omitempty"`

	// (String)
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type SCIMUserParameters struct {

	// (Boolean)
	// +kubebuilder:validation:Optional
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (Attributes Set) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Emails []EmailsParameters `json:"emails,omitempty" tf:"emails,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// SCIMUserSpec defines the desired state of SCIMUser
type SCIMUserSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SCIMUserParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SCIMUserInitParameters `json:"initProvider,omitempty"`
}

// SCIMUserStatus defines the observed state of SCIMUser.
type SCIMUserStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SCIMUserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SCIMUser is the Schema for the SCIMUsers API. Provides a JFrog SCIM User https://jfrog.com/help/r/jfrog-platform-administration-documentation/scim resource to manage users with the SCIM protocol.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,jfrog-platform}
type SCIMUser struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.emails) || (has(self.initProvider) && has(self.initProvider.emails))",message="spec.forProvider.emails is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec   SCIMUserSpec   `json:"spec"`
	Status SCIMUserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SCIMUserList contains a list of SCIMUsers
type SCIMUserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SCIMUser `json:"items"`
}

// Repository type metadata.
var (
	SCIMUser_Kind             = "SCIMUser"
	SCIMUser_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SCIMUser_Kind}.String()
	SCIMUser_KindAPIVersion   = SCIMUser_Kind + "." + CRDGroupVersion.String()
	SCIMUser_GroupVersionKind = CRDGroupVersion.WithKind(SCIMUser_Kind)
)

func init() {
	SchemeBuilder.Register(&SCIMUser{}, &SCIMUserList{})
}
